# Generated by Django 3.1.5 on 2021-01-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
