# Generated by Django 3.1.5 on 2021-01-29 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='location',
        ),
    ]
