# Generated by Django 3.1.5 on 2021-01-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_images_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
